name: rocm
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - archspec=0.2.5=pyhd8ed1ab_0
  - arrow-cpp=0.2.post=0
  - aws-c-auth=0.6.21=h774e2f3_1
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.17=h52dae97_0
  - aws-c-http=0.6.29=hf21410f_0
  - aws-c-io=0.13.11=h2666983_0
  - aws-c-mqtt=0.7.13=hefb3e95_10
  - aws-c-s3=0.2.1=h927de71_2
  - aws-c-sdkutils=0.1.7=hf5f93bc_0
  - aws-checksums=0.1.14=h6027aba_0
  - aws-crt-cpp=0.18.16=ha7c8eef_6
  - aws-sdk-cpp=1.11.2=h32f6703_0
  - blas=1.0=mkl
  - blosc=1.21.6=hef167b5_0
  - boltons=25.0.0=pyhd8ed1ab_0
  - boost-cpp=1.85.0=h44aadfe_2
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py310h6a678d5_8
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - c-blosc2=2.12.0=h80c7b02_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=25.11.1=py310hff52083_0
  - conda-libmamba-solver=25.11.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - cpp-expected=1.1.0=hff21bea_1
  - curl=8.16.0=he2463ab_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dask-core=2024.8.2=py310h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - distro=1.9.0=pyhd8ed1ab_1
  - expat=2.6.4=h6a678d5_0
  - fmt=11.1.4=h07f6e7f_1
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.14.1=ha770c72_0
  - frozendict=2.4.7=py310h7c4b9e2_0
  - gettext=0.25.1=h5888daf_0
  - gettext-tools=0.25.1=h5888daf_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.72.1=h6239696_0
  - glib-tools=2.72.1=h6239696_0
  - glog=0.5.0=h6a678d5_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h2=4.3.0=pyhcf101f3_0
  - hdf5=1.12.1=h2b7332f_3
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jemalloc=5.3.0=h5888daf_1
  - jpeg=9e=h5eee18b_3
  - jq=1.7.1=h5eee18b_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jupyterlab-variableinspector=3.1.0=py310h06a4308_0
  - jxrlib=1.1=h7b6447c_2
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libaec=1.1.3=h6a678d5_0
  - libarchive=3.7.7=hadbb8c3_0
  - libasprintf=0.25.1=h8e693c7_0
  - libasprintf-devel=0.25.1=h8e693c7_0
  - libavif=1.1.1=h5eee18b_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.85.0=hba137d9_2
  - libboost-devel=1.85.0=h00ab1b0_2
  - libboost-headers=1.85.0=ha770c72_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcblas=3.9.0=13_h8e06fc2_netlib
  - libclang13=14.0.6=default_h9986a30_1
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libfaiss=1.9.0=hf65b397_0_cpu
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgettextpo=0.25.1=h5888daf_0
  - libgettextpo-devel=0.25.1=h5888daf_0
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.72.1=h2d90d5f_0
  - libgomp=15.2.0=he0feb66_16
  - libgrpc=1.71.0=h8e591d7_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hfac485b_1
  - libjemalloc=5.3.0=h5888daf_1
  - liblapack=3.9.0=13_h8876d29_netlib
  - libllvm14=14.0.6=hcd5def8_4
  - libmamba=2.2.0=h8dd7f75_0
  - libmambapy=2.2.0=py310hbe3e362_0
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.53=h421ea60_0
  - libpq=12.20=hdbd6064_0
  - libprotobuf=5.29.3=h7460b1f_3
  - libre2-11=2025.06.26=hba17884_0
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.35=h9463b59_0
  - libspatialindex=1.9.3=h2531618_0
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.5=hfdd30dd_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h7b6447c_2
  - menuinst=2.4.2=py310hff52083_0
  - mkl=2023.1.0=h213fc3f_46344
  - msgpack-python=1.1.2=py310h03d9f68_1
  - mysql=5.7.20=hf484d3e_1001
  - nbconvert-core=7.16.4=py310h06a4308_1
  - nbconvert-pandoc=7.16.4=hd3eb1b0_1
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.11.3=he02047a_1
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - oniguruma=6.9.7.1=h27cfd23_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.0=h372e9aa_0
  - packaging=25.0=pyh29332c3_1
  - pandoc=2.12=h06a4308_3
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.47=haa7fec5_0
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py310h7c4b9e2_3
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.1=py310h0016290_0
  - python=3.10.14=h955ad1f_0
  - python-fastjsonschema=2.20.0=py310h06a4308_0
  - python-lmdb=1.4.1=py310h6a678d5_0
  - python_abi=3.10=2_cp310
  - qt-main=5.15.2=h53bd1ea_10
  - qt-webengine=5.15.9=he2071f7_8
  - re2=2025.06.26=h9925aae_0
  - readline=8.3=h853b02a_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.5=pyhcf101f3_1
  - ruamel.yaml=0.18.17=py310h139afa4_2
  - ruamel.yaml.clib=0.2.15=py310h139afa4_1
  - s2n=1.3.27=hdbd6064_0
  - simdjson=3.13.0=h84d6215_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.51.1=hbc0de68_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tqdm=4.67.1=pyhd8ed1ab_1
  - truststore=0.10.4=pyhcf101f3_0
  - unixodbc=2.3.11=h5eee18b_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_1
  - zeromq=4.3.5=h6a678d5_0
  - zfp=1.0.0=h6a678d5_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.0.7=h5eee18b_0
  - zope=1.0=py310h06a4308_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.1.0
      - accelerate==1.12.0
      - ai21==4.3.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiolimiter==1.2.1
      - aiosignal==1.4.0
      - alembic==1.17.2
      - altair==6.0.0
      - amd-cupy==13.5.1
      - amd-hipdf==2.0.0
      - amd-hipmm==3.0.0
      - amd-libhipdf==2.0.0
      - amd-pylibhipdf==2.0.0
      - anndata==0.11.4
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.75.0
      - anyio==4.12.0
      - apache-tvm-ffi==0.1.6
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - array-api-compat==1.12.0
      - arrow==1.4.0
      - arxiv==2.3.1
      - astor==0.8.1
      - asttokens==3.0.1
      - astunparse==1.6.3
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - asyncio==4.0.0
      - attrs==25.4.0
      - babel==2.17.0
      - backoff==2.2.1
      - bce-python-sdk==0.9.56
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.3
      - black==25.12.0
      - blake3==1.0.8
      - bleach==6.3.0
      - blinker==1.9.0
      - boto3==1.42.17
      - botocore==1.42.17
      - bottleneck==1.6.0
      - build==1.4.0
      - cachetools==5.5.2
      - cbor2==5.7.1
      - cffi==2.0.0
      - chessnut==0.4.1
      - chromadb==1.4.0
      - click==8.2.1
      - cloudpickle==3.1.2
      - cohere==5.15.0
      - coloredlogs==15.0.1
      - comm==0.2.3
      - compressed-tensors==0.12.2
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cuda-bindings==13.1.1
      - cuda-pathfinder==1.3.3
      - cuda-python==13.1.1
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - dacite==1.8.1
      - databricks-sdk==0.76.0
      - dataclasses-json==0.6.7
      - datalayer-pycrdt==0.12.17
      - datasets==3.2.0
      - dawg-python==0.7.2
      - debugpy==1.8.19
      - decorator==5.2.1
      - deepmerge==2.0
      - defusedxml==0.7.1
      - depyf==0.20.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distributed==2024.8.2
      - dnspython==2.8.0
      - docker==7.1.0
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - durationpy==0.10
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - faiss-cpu==1.13.2
      - farama-notifications==0.0.4
      - fastapi==0.128.0
      - fastar==0.8.0
      - fastavro==1.12.1
      - fastrlock==0.8.3
      - feedparser==6.0.12
      - filelock==3.20.1
      - filetype==1.2.0
      - flashinfer-python==0.5.3
      - flask==3.1.2
      - flask-cors==6.0.2
      - flatbuffers==24.12.23
      - fonttools==4.61.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2024.9.0
      - future==1.0.0
      - gast==0.6.0
      - gensim==4.4.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.9.0
      - google-api-core==2.28.1
      - google-auth==2.45.0
      - google-auth-oauthlib==1.0.0
      - google-cloud-aiplatform==1.132.0
      - google-cloud-bigquery==3.39.0
      - google-cloud-core==2.5.0
      - google-cloud-resource-manager==1.15.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.8.0
      - google-genai==1.56.0
      - google-pasta==0.2.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - gpt4all==2.8.2
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.3.0
      - grpc-google-iam-v1==0.14.3
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - gunicorn==23.0.0
      - gymnasium==1.2.3
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hip-python==7.0.2.555.39
      - hip-python-as-cuda==7.0.2.555.39
      - hipdf==0.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huey==2.5.5
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - imageio==2.37.2
      - imbalanced-learn==0.14.1
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - interegular==0.3.3
      - intervaltree==3.2.1
      - ipykernel==7.1.0
      - ipymarkup==0.9.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxlib==0.4.38
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.3
      - json5==0.12.1
      - jsonpath-ng==1.7.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-ai==2.31.7
      - jupyter-ai-magics==2.31.7
      - jupyter-client==8.7.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-fileid==0.9.3
      - jupyter-server-terminals==0.5.3
      - jupyter-server-ydoc==2.2.0
      - jupyter-ydoc==3.3.3
      - jupyterlab==4.5.1
      - jupyterlab-night==0.5.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kaleido==0.2.1
      - keras==3.7.0
      - kiwisolver==1.4.9
      - kubernetes==34.1.0
      - langchain==0.3.27
      - langchain-anthropic==0.3.22
      - langchain-aws==0.2.35
      - langchain-cohere==0.4.5
      - langchain-community==0.3.31
      - langchain-core==0.3.81
      - langchain-google-genai==2.1.12
      - langchain-google-vertexai==2.1.2
      - langchain-mistralai==0.2.12
      - langchain-nvidia-ai-endpoints==0.3.19
      - langchain-ollama==0.3.10
      - langchain-openai==0.3.35
      - langchain-text-splitters==0.3.11
      - langsmith==0.5.1
      - lark==1.2.2
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning-utilities==0.14.3
      - llguidance==1.3.0
      - llvmlite==0.43.0
      - lm-format-enforcer==0.11.3
      - locket==1.0.0
      - logsett==2023.0.0
      - loguru==0.7.2
      - magic-filter==1.0.12
      - mako==1.3.10
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistral-common==1.8.6
      - mistune==3.2.0
      - ml-dtypes==0.3.2
      - mlflow==3.8.1
      - mlflow-skinny==3.8.1
      - mlflow-tracing==3.8.1
      - mmh3==5.2.0
      - model-hosting-container-standards==0.1.12
      - mpmath==1.3.0
      - msgspec==0.20.0
      - multidict==6.7.0
      - multimethod==1.12
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - namex==0.0.8
      - narwhals==2.14.0
      - natasha==1.6.0
      - natsort==8.4.0
      - navec==0.10.0
      - nbclient==0.10.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.9.2
      - notebook==7.5.1
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numba-hip==0.1.3
      - numexpr==2.14.1
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.3
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.2.2
      - ollama==0.6.1
      - onnx==1.17.0
      - onnxruntime==1.15.1
      - onnxruntime-extensions==0.13.0
      - openai==2.14.0
      - opencv-python==4.9.0.80
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-grpc==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - opt-einsum==3.4.0
      - optimum==1.23.3
      - optimum-amd==0.1.0
      - optree==0.13.1
      - orjson==3.10.12
      - outlines-core==0.2.11
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - partd==1.4.2
      - pathspec==0.12.1
      - patsy==1.0.2
      - pettingzoo==1.25.0
      - pexpect==4.9.0
      - pillow==11.3.0
      - pipdeptree==2.30.0
      - plotly==6.5.0
      - ply==3.11
      - posthog==5.4.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==6.33.2
      - psutil==7.2.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py4j==0.10.9.9
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.3
      - pycountry==24.6.1
      - pycparser==2.23
      - pycrdt-store==0.1.3
      - pycrdt-websocket==0.16.0
      - pycryptodome==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pygments==2.19.2
      - pymorphy2==0.9.1
      - pymorphy2-dicts-ru==2.4.417127.4579844
      - pymupdf==1.26.7
      - pyparsing==3.3.1
      - pypdf==6.5.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.16.1
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.16
      - pyspark==4.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - pytokens==0.3.0
      - pytorch-lightning==2.5.1.post0
      - pytorch-triton-rocm==3.1.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qianfan==0.4.12.3
      - rank-bm25==0.2.2
      - ray==2.52.1
      - razdel==0.5.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rich-toolkit==0.17.1
      - rignore==0.7.6
      - rocm-llvm-python==7.0.2.555.42
      - rpds-py==0.30.0
      - rsa==4.9
      - ruwordnet==0.0.6
      - s3transfer==0.16.0
      - safetensors==0.4.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentence-transformers==4.1.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.48.0
      - session-info==1.0.1
      - setproctitle==1.3.7
      - setuptools==80.9.0
      - sgmllib3k==1.0.0
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - sklearn-compat==0.1.5
      - slovnet==0.6.0
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8.1
      - sqlalchemy==1.4.54
      - sqlite-anyio==0.2.3
      - sqlparse==0.5.5
      - stable-baselines3==2.7.1
      - stack-data==0.6.3
      - starlette==0.50.0
      - statsmodels==0.14.6
      - stdlib-list==0.11.1
      - streamlit==1.52.2
      - supervisor==4.3.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tblib==3.2.2
      - tenacity==8.5.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.12.0
      - tinycss2==1.5.1
      - together==1.5.34
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.3.0
      - toolz==1.1.0
      - torch==2.5.1+rocm6.2
      - torchaudio==2.5.1+rocm6.2
      - torchclust==1.0.0
      - torchgmm==0.1.2
      - torchmetrics==1.7.3
      - torchvision==0.20.1+rocm6.2
      - tornado==6.5.4
      - traitlets==5.14.3
      - transformers==4.57.3
      - triton==3.5.0
      - typeguard==4.4.1
      - typer==0.19.2
      - types-pyyaml==6.0.12.20250915
      - types-requests==2.32.0.20241016
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.3.0
      - uuid-utils==0.12.0
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - validators==0.35.0
      - visions==0.7.6
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.4
      - wget==3.2
      - widgetsnbextension==4.0.15
      - win32-setctime==1.1.0
      - wordcloud==1.9.4
      - wrapt==2.0.1
      - xgrammar==0.1.27
      - xxhash==3.5.0
      - yargy==0.16.0
      - yarl==1.22.0
      - zict==3.0.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /home/gna/anaconda3/envs/rocm
